### ISSUE TITLE
Feature: Go to on enter

### ISSUE THREAD

**Issue by falco010** [Skullsneeze/Localhost-disco#3]
Als je een project zoekt en er is maar 1 element gevonden, wil ik gelijk naar het project(trunk) gaan als ik op enter druk.

Misschien als fallback als er meerdere elementen zijn gevonden om de eerst gevonden bij enter te pakken? Stel dat je toch naar de branch wil, klik je maar lekker erop ipv gelijk enter!

**Comment by Skullsneeze** [comment]
Functionality added in commit `94bb6c69e07f0c5e074fa063049ef10426f8405a`
