### ISSUE TITLE
A demo in the readme?

### ISSUE THREAD

**Issue by math2001** [Skullsneeze/Localhost-disco#4]
Hi!

Can you add a demo in your readme? (an image)

Matt

**Comment by Skullsneeze** [comment]
Hi @math2001, Good idea. I never really thought anyone would find this interesting, so documentation is very limited. Will work on that soon!

**Comment by math2001** [comment]
Cool!

**Comment by Skullsneeze** [comment]
Hi Math, again, sorry for the delay.

I've added a demo in the readme!
